### ISSUE TITLE
We need a to do list

### ISSUE THREAD

**Issue by brennanpincardiff** [DaveRGP/secretSantR#1]
We need to write a to do list.
Also I need to test this way of working....

**Comment by DaveParr** [comment]
So in develop is effectively a mwe. It will allow a user to put their name in, and assign one of the un-assigned topics to the name.

Visually, this just moves a row from the top table to the bottom table with the name filled out, still to do is:

- [ ] mulligans/re-roll
- [ ] validation of the name, so it's at the least not blank
- [ ] validation of the names to be distinct from other names already given

**Comment by DaveParr** [comment]
made 2 issues in the tracker, that's our to do list :)
