### ISSUE TITLE
need to make a system to allow reassignment once only per name

### ISSUE THREAD

**Issue by DaveParr** [DaveRGP/secretSantR#2]
re-roll/mulligan once per name to generate a new topic

**Comment by DaveParr** [comment]
this could be with persistent storage of unique users, which have had their single mulligan, which would allow users to go back and re-roll

or

could be part of user validation, with the app suggesting a topic, and the app allowing them to either accept and lock it in, or reselect only once, and lock in the second selected topic

**Comment by stephlocke** [comment]
Yah - do it in the shiny layer! Just hold a variable that says whether
they've hit the mulligan button or not.
